# ref. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    assignees:
      - sue445

  - package-ecosystem: gomod
    directory: /ext/funnel_http/
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Asia/Tokyo
    cooldown:
      default-days: 7
    open-pull-requests-limit: 99
    assignees:
      - sue445
