module FunnelHttp
  VERSION: String
  USER_AGENT: String

  type fuzzy_header = Hash[String, String | Array[String]]

  type fuzzy_request = {
    method: String | Symbol,
    url: String,
    header: fuzzy_header?,
    body: String?,
  }

  type strict_header = Hash[String, Array[String]]

  type strict_request = {
    method: String,
    url: String,
    header: strict_header,
    body: String?,
  }

  type response = {
    url: String,
    status_code: Integer,
    body: String,
    header: strict_header
  }

  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
end
