name: Publish gem to rubygems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo-name:       sue445/funnel_http
      gem-name:        funnel_http
      ruby-version:    .tool-versions
      go-version-file: ext/funnel_http/go.mod
    permissions:
      contents: write
      id-token: write
